---
# task install

- name: disable selinux
  selinux:
    state: disabled

- name: install all repos
  yum:
    name: "{{ eon_packages }}"
    state: latest

- name: grafana - add repository
  yum_repository:
    name: grafana
    description: grafana
    baseurl: "{{ grafana_repo }}"
    gpgcheck: yes
    gpgkey: "{{ grafana_repo_key }}"
  when:
    - eon_version == 5
    - eon_release == 3

- name: influxdb - add repository
  yum_repository:
    name: influxdb
    description: influxdb
    baseurl: "{{ influxdb_repo }}"
    gpgcheck: yes
    gpgkey: "{{ influxdb_repo_key }}"
  when:
    - eon_version == 5
    - eon_release == 3


- name: influxdb - import rpm key
  rpm_key:
    key: "{{ influxdb_repo_key }}"
    state: present
  when:
    - eon_version == 5
    - eon_release == 3


- name: install the latest 'eyesofnetwork-release' package
  yum:
    name: "eyesofnetwork-release"
    state: latest
    update_cache: yes

- name: install the 'EyesOfNetwork Monitoring' package group
  yum:
    name: "@^EyesOfNetwork Monitoring"
    state: latest
    enablerepo: eon-base
    update_cache: yes
    exclude: php-mysql

- name: check if eon repo exists
  stat: path=/srv/eyesofnetworkrepo
  register: check_path

- name: start eyesofnetwork initialization
  service:
    name: eonconf
    state: started
  when: check_path.stat.exists == false

- name: wait until eyesofnetwork installed
  wait_for:
    path: /srv/eyesofnetworkrepo/extras
    state: present
    msg: "EyesOfNetwork is not installed !"
